title: "Docker"
script: "code/docker/docker.sh"
icon: "ğŸ‹"
items:
  - icon: "ğŸ“‹"
    label: "ps"
    action: "ps"

  - icon: "ğŸ³"
    label: "shell"
    action: "shell"


  - icon: "âš¡"
    label: "ephemeral"
    action: "ephemeral"


  - icon: "ğŸ“œ"
    label: "logs"
    action: "logs"


  - icon: "ğŸ›ï¸"
    label: "TUI"
    action: "tui"


  - icon: "ğŸ’¥"
    label: "Destroy"
    action: "destroy"

